[workspace]
resolver = "3"
members = ["hmi", "vda5050-data-types"]

[workspace.dependencies]
# High-performance JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = "0.13" # Optional: Requires RUSTFLAGS="-C target-feature=+avx2"
